/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../packages/browser/src/routes/__root'
import { Route as IndexRouteImport } from './../../packages/browser/src/routes/index'
import { Route as AboutRouteImport } from './../../packages/browser/src/routes/about'
import { Route as ConnectionsRouteImport } from './../../packages/browser/src/routes/connections'
import { Route as SignInRouteImport } from './../../packages/browser/src/routes/sign-in'
import { Route as ConnectionsIndexRouteImport } from './../../packages/browser/src/routes/connections.index'
import { Route as ConnectionsSplatRouteImport } from './../../packages/browser/src/routes/connections.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ConnectionsSplatRoute = ConnectionsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ConnectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/connections/$': typeof ConnectionsSplatRoute
  '/connections/': typeof ConnectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/connections/$': typeof ConnectionsSplatRoute
  '/connections': typeof ConnectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/connections/$': typeof ConnectionsSplatRoute
  '/connections/': typeof ConnectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connections'
    | '/sign-in'
    | '/connections/$'
    | '/connections/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/sign-in' | '/connections/$' | '/connections'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connections'
    | '/sign-in'
    | '/connections/$'
    | '/connections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/connections/$': {
      id: '/connections/$'
      path: '/$'
      fullPath: '/connections/$'
      preLoaderRoute: typeof ConnectionsSplatRouteImport
      parentRoute: typeof ConnectionsRoute
    }
  }
}

interface ConnectionsRouteChildren {
  ConnectionsSplatRoute: typeof ConnectionsSplatRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsSplatRoute: ConnectionsSplatRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
